In [3]:
import spacy
import nltk
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('spam.csv')

In [7]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [19]:
df[df['Category']=='spam']['Message'].iloc[1]

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"

In [21]:
df[df['Category']=='spam']['Message'].iloc[2]

'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.'

In [25]:
df[df['Category']=='ham']['Message'].iloc[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [27]:
df[df['Category']=='ham']['Message'].iloc[1]

'Ok lar... Joking wif u oni...'

In [39]:
df[df['Category']=='ham']['Message'].iloc[2]

'U dun say so early hor... U c already then say...'

In [41]:
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [47]:
df['spam'].value_counts()

0    4825
1     747
Name: spam, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(df['Message'],df['spam'],test_size=0.2)

In [53]:
X_train.shape, X_test.shape

((4457,), (1115,))

In [59]:
type(X_train), type(X_test)

(pandas.core.series.Series, pandas.core.series.Series)

In [61]:
X_train[:4]

1234                   Lol ok. I'll snatch her purse too.
454     Ok i will tell her to stay out. Yeah its been ...
465                         Ok i am on the way to railway
1725              There bold 2  &lt;#&gt; . Is that yours
Name: Message, dtype: object

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
v = CountVectorizer()

In [73]:
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7760 sparse matrix of type '<class 'numpy.int64'>'
	with 59519 stored elements in Compressed Sparse Row format>

In [75]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
X_train_cv.shape

(4457, 7760)

In [85]:
v.get_feature_names_out()[1000:1050]

array(['anywhere', 'aom', 'apart', 'apartment', 'apes', 'apeshit',
       'aphex', 'apnt', 'apo', 'apologetic', 'apologise', 'apologize',
       'app', 'apparently', 'appeal', 'appear', 'apples', 'application',
       'apply', 'applyed', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approve', 'approved', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aptitude', 'aquarius', 'ar',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking'], dtype=object)

In [87]:
v.vocabulary_

{'lol': 4174,
 'ok': 4898,
 'll': 4147,
 'snatch': 6261,
 'her': 3398,
 'purse': 5495,
 'too': 6969,
 'will': 7528,
 'tell': 6742,
 'to': 6928,
 'stay': 6449,
 'out': 4992,
 'yeah': 7692,
 'its': 3746,
 'been': 1289,
 'tough': 6995,
 'but': 1571,
 'we': 7424,
 'are': 1044,
 'optimistic': 4954,
 'things': 6835,
 'improve': 3622,
 'this': 6844,
 'month': 4566,
 'am': 930,
 'on': 4917,
 'the': 6805,
 'way': 7420,
 'railway': 5543,
 'there': 6824,
 'bold': 1410,
 'lt': 4240,
 'gt': 3242,
 'is': 3728,
 'that': 6801,
 'yours': 7728,
 'waiting': 7365,
 'for': 2926,
 'your': 7725,
 'call': 1600,
 'sir': 6169,
 'where': 7492,
 'at': 1110,
 'were': 7468,
 'hungry': 3535,
 'sun': 6595,
 'ah': 865,
 'thk': 6845,
 'mayb': 4390,
 'can': 1623,
 'if': 3586,
 'dun': 2482,
 'have': 3342,
 'anythin': 994,
 'book': 1419,
 'lesson': 4070,
 'pilates': 5202,
 'orchard': 4964,
 'mrt': 4602,
 'noe': 4783,
 'hor': 3483,
 'oh': 4893,
 'come': 1901,
 'tomorrow': 6956,
 'haha': 3280,
 'my': 4652,
 'friend': 2990,


In [91]:
v.get_feature_names_out()[7692]

'yeah'

In [95]:
X_train_np = X_train_cv.toarray()

In [99]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [101]:
np.where(X_train_np[0]!=0)

(array([3398, 4147, 4174, 4898, 5495, 6261, 6969]),)

In [107]:
X_train_np[0][3398]

1

In [109]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [111]:
from sklearn.naive_bayes import MultinomialNB

In [113]:
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [115]:
X_test_cv = v.transform(X_test)

In [121]:
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [123]:
y_pred = model.predict(X_test_cv)

In [125]:
from sklearn.metrics import classification_report

In [131]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       964
           1       0.95      0.91      0.93       151

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [133]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])