In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[16, 26]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[9, 1], [16, 26], [18, 16], [1, 19, 23], [22, 3, 19], [10, 1], [16, 3, 29], [8, 27], [8, 2], [21, 3]]


In [4]:
encoded_reviews

[[9, 1],
 [16, 26],
 [18, 16],
 [1, 19, 23],
 [22, 3, 19],
 [10, 1],
 [16, 3, 29],
 [8, 27],
 [8, 2],
 [21, 3]]

In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 9  1  0]
 [16 26  0]
 [18 16  0]
 [ 1 19 23]
 [22  3 19]
 [10  1  0]
 [16  3 29]
 [ 8 27  0]
 [ 8  2  0]
 [21  3  0]]


In [6]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [26]:
model.fit(X, y, epochs=50, verbose=0)

In [29]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 1ms/step - loss: 0.6384 - accuracy: 1.0000


1.0

In [30]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [31]:
weights[13]

array([-0.08330977, -0.06752131, -0.04629624, -0.00765801, -0.02024159],
      dtype=float32)

In [32]:
weights[4]

array([-0.07935128, -0.08574004,  0.06615968, -0.02349528,  0.00917289],
      dtype=float32)

In [33]:
weights[16]

array([ 0.0128377 ,  0.03549778,  0.05134471, -0.07147218,  0.03261041],
      dtype=float32)